### ISSUE TITLE
Register problem

### ISSUE THREAD

**Issue by varungoud2000** [imShakil/BloodBank#26]
when i registering the account it showing in contact place as enter valid no but i kept valid number only

**Comment by imShakil** [comment]
Hi @varungoud2000 
Actually, This app is made only for Bangladesh. So, you might be getting issues because your number doesn't meet [this](https://github.com/imShakil/BloodBank/blob/master/app/src/main/java/com/android/iunoob/bloodbank/activities/ProfileActivity.java#L162) requirements.

**Comment by c7355053-sudo** [comment]
Mine says" register faild try again"
