### ISSUE TITLE
Request for Documentation

### ISSUE THREAD

**Issue by Chandra-shekar-shetty** [imShakil/BloodBank#4]
Sir can u please provide a structure of Db...On snapshop of all the tables will be appriciable

**Comment by rashjadhav** [comment]
Sir can u please provide a structure of Db...On snapshop of all the tables will be appriciable

**Comment by imShakil** [comment]
Hi all! Database snapshots are added, see the below link.
https://github.com/imShakil/BloodBank/wiki/Databse-Snapshots
